version: 2
jobs:
  lint:
    machine:
      ruby:
        version: 2.4.1
    steps:
      - checkout
      - run:
          name: Installing linter
          command: gem install awesome_bot
      - run:
          name: Linting
          command: awesome_bot --skip-save-result --allow-ssl --allow-timeout --allow-dupe --allow-redirect --white-list *.md

workflows:
  version: 2
  all:
    jobs:
      - lint
